### ISSUE TITLE
Issue with settings menu returning null; crashing 

### ISSUE THREAD

**Issue by MusaMahmood** [MusaMahmood/Android-BLE-Kotlin-Sample#11]
`FATAL EXCEPTION: main
                                                                                         Process: com.yeolabgt.mahmoodms.androidblekotlin, PID: 28129
                                                                                         java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=0, data=null} to activity {com.yeolabgt.mahmoodms.androidblekotlin/com.yeolabgt.mahmoodms.androidblekotlin.DeviceControlActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
                                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:4525)
                                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:4568)
                                                                                             at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1706)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:154)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6688)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                                          Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
                                                                                             at com.yeolabgt.mahmoodms.androidblekotlin.DeviceControlActivity.onActivityResult(DeviceControlActivity.kt:0)
                                                                                             at android.app.Activity.dispatchActivityResult(Activity.java:7226)
                                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:4521)
                                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:4568) 
                                                                                             at android.app.ActivityThread.-wrap22(ActivityThread.java) 
                                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1706) 
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                             at android.os.Looper.loop(Looper.java:154) 
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6688) 
                                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) `

**Comment by MusaMahmood** [comment]
fixed; make returned data: Intent nullable, by adding question mark. 
needed to change:
`override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent) {`
to
[override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {](url)
